apiVersion: v1
kind: Secret
metadata:
  name: mongodb-atlas
type: Opaque
data:
  mongodb.uri.accounts: bW9uZ29kYitzcnY6Ly9kZW1vLXVzZXI6aXIyNmwxWTAyTVczSXBIQkB4eWxpYS1jbHVzdGVyLWlpNWVrLmdjcC5tb25nb2RiLm5ldC9hY2NvdW50cwo=
  mongodb.uri.orders: bW9uZ29kYitzcnY6Ly9kZW1vLXVzZXI6aXIyNmwxWTAyTVczSXBIQkB4eWxpYS1jbHVzdGVyLWlpNWVrLmdjcC5tb25nb2RiLm5ldC9vcmRlcnMK
