server:
  port: 8888
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8888/eureka

spring:
  application:
    name: eureka-discovery

---
server:
  port: 8888
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8888/eureka

spring:
  profiles:
    docker
  application:
    name: eureka-discovery