server:
  port: 8085
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: orders
  data:
    mongodb:
       uri: mongodb+srv://demo-user:ir26l1Y02MW3IpHB@xylia-cluster-ii5ek.gcp.mongodb.net/orders

  kafka:
    bootstrap-servers: pkc-43n10.us-central1.gcp.confluent.cloud:9092
    topic:
      accounts-customer: accounts.customer.change
    consumer:
      group-id: orders
      auto-offset-reset: earliest

    properties:
      request:
        timeout:
          ms: 20000
      retry:
        backoff:
          ms: 500
      ssl:
        endpoint:
          identification:
            algorithm: https
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="R3WJ6RVP26CPBWLR" password="M+gI3JYjRNDbg/qJyCZz550rXwUgSqY1Euhy9glWXrhyu9sTPCFTUvfuPPZKUb16";
      security:
        protocol: SASL_SSL

management:
  endpoints:
    web:
      exposure:
        include: heapdump, loggers, prometheus, threaddump, info, metrics, health, hystrix.stream
  health:
    defaults:
      enabled: false
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
---
server:
  port: 8080
spring:
  profiles: gke
  data:
    mongodb:
      uri: mongodb://mongo:27017/orders
  kafka:
    bootstrap-servers: kafka:9092

logging:
  level:
    root: INFO
